name: Pull request

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
        working-directory: ./src/indoe-navi-control/
      
